Models/EmployerModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ElmarakbyTest.Models
{
    public class EmployerModel
    {
        public int? Id { get; set; }

        [Required , StringLength(100)]
        public string Name { get; set; }

        [Required, StringLength(100)]
        public string Title { get; set; }

        [Required]
        public float Salary { get; set; }

        public string? ImagePath { get; set; }

        public IFormFile? Image { get; set; }
    }
}

Controllers/EmployersController.cs
using ElmarakbyTest.Models;
using ElmarakbyTest.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ElmarakbyTest.Controllers
{
    public class EmployersController : Controller
    {
        private readonly IEmployerRepository _employerRepository = null;
        
        public EmployersController(IEmployerRepository employerRepository) 
        {
            _employerRepository = employerRepository;
        }

        // GET: EmployersController
        [Route("~/")]
        [Route("~/home")]
        [Route("~/employers")]
        public ActionResult Index()
        {
            var employers = _employerRepository.Get();
            return View(employers);
        }

        // GET: EmployersController/Details/5
        public ActionResult Details(int id)
        {
            if (id <= 0)
                return NotFound();

            var employer = _employerRepository.GetById(id);
            if (employer == null)
                return NotFound();

            return View(employer);
        }

        // GET: EmployersController/Create
        public ActionResult Create()
        {
            var model = new EmployerModel();
            return View(model);
        }

        // POST: EmployersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([FromForm] EmployerModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Image != null)
                {
                    model.Id = _employerRepository.Add(model);
                    if (model.Id > 0)
                        return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }

        // GET: EmployersController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _employerRepository.GetById(id);
            return View(model);
        }

        // POST: EmployersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [FromForm] EmployerModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Image != null)
                {
                    int result = _employerRepository.Update(id, model);

                    if (result > 0)
                        return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }

        // GET: EmployersController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _employerRepository.GetById(id);
            return View(model);
        }

        // POST: EmployersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [FromForm] EmployerModel model)
        {
            if (id == model.Id)
            {
                var result = _employerRepository.Delete(id);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Edit), new { Id = id });
        }
    }
}

Views/Employers/Create.cshtml
@model EmployerModel

@{
    ViewData["Title"] = "Create Employer";
}

<div class="container">
   <h4 class="h1 mb-5">Create Employer</h4>
   <hr />
   <div class="row">
       <div class="col-md-6 mb-5">
           <form asp-action="Create" asp-controller="Employers" enctype="multipart/form-data">
               <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               <div class="form-group mb-3">
                   <label asp-for="Name"></label>
                   <input asp-for="Name" class="form-control" />
                   <span asp-validation-for="Name" class="text-danger"></span>
               </div>
               <div class="form-group mb-3">
                   <label asp-for="Title"></label>
                   <input asp-for="Title" class="form-control" />
                   <span asp-validation-for="Title" class="text-danger"></span>
               </div>

            <div class="form-group mb-3">
               <label asp-for="Salary"></label>
               <input asp-for="Salary" class="form-control" />
               <span asp-validation-for="Salary" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
               <label asp-for="Image"></label>
               <input asp-for="Image" class="form-control" />
               <span asp-validation-for="Image" class="text-danger"></span>
            </div>
               
               <button type="submit" class="btn btn-primary">Add</button>
               
           </form>
       </div>
   </div>

   <div>
       <a asp-action="Index">Back to Home</a>
   </div>
</div>

Views/Employers/Delete.cshtml
@model EmployerModel

@{
    ViewData["Title"] = $"Delete | { Model.Name }";
}

<div class="container text-center">
   <h4 class="h1 mb-5">@Model.Name</h4>
   <p class="text-muted">you are now going to delete the Employer Permenantly</p>
   <p class="text-muted">the operation cannot be undone, whould you like to proceed?</p>
   <div>
      <form asp-action="Delete">
         <input type="hidden" asp-for="Id" />
         <input type="submit" value="Delete" class="btn btn-danger" /> |
         <a asp-action="Index">Back to Home</a>
      </form>
   </div>
</div>

Views/Employers/Details.cshtml
@model EmployerModel

@{
    ViewData["Title"] = Model.Name;
}

<div class="container">
   <div class="row">
      <div class="col-7">
         <img src="@Model.ImagePath" class="img-thumbnail" alt="Profile Photo">
      </div>
      <div class="col-5">
         <h4 class="h1 mb-5">@Model.Name</h4>
         <p class="text-muted">@Model.Title</p>
         <p class="text-muted">@Model.Salary</p>
         <div>
            <a class="text-success" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
            <a class="text-danger" asp-action="Delete" asp-route-id="@Model?.Id">Delete</a> |
            <a class="text-dark" asp-action="Index">Back to List</a>
         </div>
      </div>
   </div>
   
</div>

Views/Employers/Edit.cshtml
@model EmployerModel

@{
    ViewData["Title"] = "Edit Employer";
}

<div class="container">
   <h4 class="h1">Edit Employer</h4>
   <hr />
   <div class="row">
       <div class="col-md-6 mb-5">
            <form asp-action="Edit" asp-controller="Employers" enctype="multipart/form-data">
               <div asp-validation-summary="ModelOnly" class="text-danger"></div>
               <div class="form-group mb-3">
                   <label asp-for="Name"></label>
                   <input asp-for="Name" class="form-control" />
                   <span asp-validation-for="Name" class="text-danger"></span>
               </div>
               <div class="form-group mb-3">
                   <label asp-for="Title"></label>
                   <input asp-for="Title" class="form-control" />
                   <span asp-validation-for="Title" class="text-danger"></span>
               </div>

            <div class="form-group mb-3">
               <label asp-for="Salary"></label>
               <input asp-for="Salary" class="form-control" />
               <span asp-validation-for="Salary" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
               <label asp-for="Image"></label>
               <input asp-for="Image" class="form-control" />
               <span asp-validation-for="Image" class="text-danger"></span>
            </div>
               
               <button type="submit" class="btn btn-primary">Update</button>
               
           </form>
       </div>
   </div>

   <div>
       <a asp-action="Index">Back to Home</a>
   </div>
</div>

Views/Employers/Index.cshtml
@{
    ViewData["Title"] = "Employers List";
}
@model IEnumerable<EmployerModel>

<div class="container">
    @if (Model == null)
    {
       <div>
          <h2 class="text-center display-4"> No Employers Found.</h2>
          <a class="btn btn-success" asp-action="Create">Add Your First Employer</a>
       </div>
    }
    else
    {
       <h3 class="display-4">All Employers</h3>
       <div class="row">
          <div class="mb-3">
             <a class="btn btn-success" asp-action="Create">Create New</a>
          </div>
          <table class="table">
             <thead>
                <tr>
                   <th scope="col">Id</th>
                   <th scope="col">Name</th>
                   <th scope="col">Title</th>
                   <th scope="col">Salary</th>
                   <th scope="col">Photo</th>
                   <th></th>
                </tr>
             </thead>
             <tbody>
               @foreach(var emp in Model)
               {
                  <tr>
                     <th scope="row">@emp.Id</th>
                     <td>@emp.Name</td>
                     <td>@emp.Title</td>
                     <td>@emp.Salary</td>
                       <td><img src="@emp.ImagePath" width="30" height="30" class="img-thumbnail rounded " alt="Profile Photo"></td>
                     <td>
                        <a class="text-primary link-primary" asp-action="Edit" asp-route-id="@emp.Id">Edit</a> |
                        <a class="text-secondary link-secondary" asp-action="Details" asp-route-id="@emp.Id">Details</a> |
                        <a class="text-danger link-danger" asp-action="Delete" asp-route-id="@emp.Id">Delete</a>
                     </td>
                  </tr>
               }
             </tbody>
          </table>
       </div>
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | Book Store App</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    
</head>
<body>

   <partial name="_header" />

   <main role="main">
        @RenderBody()
    </main>
    
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
   @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_header.cshtml
<header>
   <nav class="navbar navbar-expand-sm bg-light border-bottom shadow mb-3">
      <div class="container">
         <a class="navbar-brand" href="#"><img src="~/images/Logo.png" width="30" height="30" /> Employers App</a>
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse d-sm-inline-flex flex-sm-row-reverse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-grow-1">
               <li class="nav-item">
                  <a class="nav-link active" aria-current="page" asp-controller="Employers" asp-action="Index">Employers</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" asp-controller="Employers" asp-action="Create">Add New</a>
               </li>
            </ul>
         </div>
      </div>
   </nav>
</header>